export const directorydata = [
  {
    name: "Anurag Singh",
    address: "Rewa, Madhya Pradesh",
    city: "Rewa",
    timeing: "8:00Am to 3:00Pm",
    phone: "939592343",
    specialist: "NeuroLogist",
  },
  {
    name: "Anurag Singh",
    address: "Rewa, Madhya Pradesh",
    city: "Rewa",
    timeing: "8:00Am to 3:00Pm",
    phone: "939592343",
    specialist: "NeuroLogist",
  },
  {
    name: "Anurag Singh",
    address: "Rewa, Madhya Pradesh",
    city: "Rewa",
    timeing: "8:00Am to 3:00Pm",
    phone: "939592343",
    specialist: "NeuroLogist",
  },
  {
    name: "Anurag Singh",
    address: "Rewa, Madhya Pradesh",
    city: "Rewa",
    timeing: "8:00Am to 3:00Pm",
    phone: "939592343",
    specialist: "NeuroLogist",
  },
  {
    name: "Anurag Singh",
    address: "Rewa, Madhya Pradesh",
    city: "Rewa",
    timeing: "8:00Am to 3:00Pm",
    phone: "939592343",
    specialist: "NeuroLogist",
  },
  {
    name: "Anurag Singh",
    address: "Rewa, Madhya Pradesh",
    city: "Rewa",
    timeing: "8:00Am to 3:00Pm",
    phone: "939592343",
    specialist: "NeuroLogist",
  },
];
